name: OpenDrupal Pegi Configuration
type: module
description: 'Installable configuration for OpenDrupal Pegi exercises.'
package: OpenDrupal 
version: 8.x-1.x
core: 8.x
dependencies:
  - drupal:entity_reference
