#
# Contains exercises for the configuration schema.
# Estimated time: 60 min.
#

# ==== Step 1 (optional) ====
# Add a configuration value for the games overview page title.
# - Add a text field for the page title to the configuration form
#   \Drupal\od_pegi\Form\OdPegiSettingsForm
# - Update the other form methods and the default value for this configuration.
# - Apply the page title to the games page.
# - Check the result.

# ==== Step 2 (optional) ====
# Create the schema for the od_pegi configuration.
# - Find examples in core of configuration schema files.
# - Check out the documentation at https://www.drupal.org/node/1905070
# - Create a schema file for the od_pegi configuration.
# - Check the configuration using the Configuration inspector module
#   https://www.drupal.org/project/config_inspector.

# --- Fragments for step 2 ---
# - config_object
# - games_page_title
# - games_per_page
# - integer
# - label
# - mapping
# - type
# - od_pegi.schema.yml
# - od_pegi.settings

# ==== Step 3 (optional) ====
# Translate the games page title.
# - Enable the following modules: Language, Configuration Translation
# - Add a second language, for example Dutch.
# - Translate the page title configuration
# - Check the result on the Dutch Games page.
